[package]
name = "permission_check"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "permission_macro",
    "permission_parser"
]

[dependencies]
permission_parser = {path = "permission_parser/", version = "0.1.0"}