[package]
name = "permission_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.106", features = ["full"] }
permission_parser = {path = "../permission_parser/"}
permission_check = { path = "../" }
quote = "1.0"
proc-macro2 = "1.0"